### PR TITLE
Ovrd feature updates

### PR DESCRIPTION
**Pull request by sohaibhasan**
#### What's this PR do?
* Adds new functionality to OVRD funnel
  - additional useful timestamps
  - counts of online drive referral beta completions tied to to an alpha
  - adds an additional useful field to public.posts from rogue.posts
  - adds comments
  - fixes a bug to allow for registration completions for this year
#### Where should the reviewer start?
 * ovrd_creator_funnel.sql
#### How should this be manually tested?
 * Runs in QA?
#### What are the relevant tickets?
* Follow-up work for this ticket: https://www.pivotaltracker.com/story/show/171886321

### CODE REVIEW

**Comment by sohaibhasan** [comment]
**PR 1000 WOOOOOOOOO**

**Comment by blisteringherb** [comment]
I'm testing this locally first, and once those run successfully I'll approve this PR so we can catch any potential errors before they're merged into master.

**Comment by blisteringherb** [comment]
@sohaibhasan I'm running into this error:
```
10:40:13 | Concurrency: 1 threads (target='qa')
10:40:13 |
10:40:13 | 1 of 1 START table model public.ovrd_creator_funnel.................. [RUN]
10:40:13 | 1 of 1 ERROR creating table model public.ovrd_creator_funnel......... [ERROR in 0.38s]
10:40:13 |
10:40:13 | Finished running 1 table model in 1.44s.

Completed with 1 error and 0 warnings:

Database Error in model ovrd_creator_funnel (models/user_journey/ovrd_creator_funnel.sql)
  missing FROM-clause entry for table "referral_completions"
  LINE 166: LEFT JOIN referral_counts ON referral_completions.referrer=b...
                                         ^
```

**Comment by sohaibhasan** [comment]
@sheyd Just pushed a fix. Can you try again?

**Pull request merged**
