### PR TITLE
Adding script to dump daily users table snapshots from Phoenix

### PR DESCRIPTION
**Pull request by sheyd**
#### What's this PR do?

First step in getting a user activity log table setup in Quasar, we're dumping Phoenix user table once a day and doing diffs.

#### Where should the reviewer start?

The script.

#### How should this be manually tested?

Tested on a Quasar Node.

#### What are the relevant tickets?

https://github.com/DoSomething/quasar/issues/273.

### CODE REVIEW

**Comment by mshmsh5000** [comment]
This doesn't do diffs, though, just does the daily table dump. So this doesn't resolve #273 right @sheyd ?

**Comment by sheyd** [comment]
@mshmsh5000 No, it doesn't. Just linked this as first PR step towards solving #273. #274 is the actually relevant ticket here, I've updated PR comments to reflect both.

**Comment by mshmsh5000** [comment]
This PR is #274 ! Anyhoo, this looks 👍 and 🌮 as a first step—at least you have the data in there. I imagine the diff-creating part will want to prune these daily snapshots eventually too.

**Comment by sheyd** [comment]
Gah, the title was too perfect for a ticket, I should have known. Yes, it will. Just making sure I have enough data aggregation over the next few day once I setup the ETL Jenkins jobs for this to continue to diff prototyping next week.

**Pull request merged**
