### PR TITLE
Adds new member-latest-messaging-status model

### PR DESCRIPTION
**Pull request by rapala61**
# What's this PR do?
- This PR adds a new model to help report and analyze our member level impact. More directly, our member addressable state.
- Adds the new models:
  - `member_latest_messaging_status`.
  - `member_latest_inbound_sms_engagement`

### Test in Production
```
$ pipenv run dbt run --model tag:core --target prod_warning
Running with dbt=0.18.1
Found 55 models, 104 tests, 3 snapshots, 0 analyses, 143 macros, 0 operations, 0 seed files, 26 sources

21:40:09 | Concurrency: 4 threads (target='prod_warning')
21:40:09 | 
21:40:09 | 1 of 2 START table model public_intermediate.member_latest_inbound_sms_engagement [RUN]
21:40:53 | 1 of 2 OK created table model public_intermediate.member_latest_inbound_sms_engagement [SELECT 1693342 in 44.14s]
21:40:53 | 2 of 2 START table model public.member_latest_messaging_status....... [RUN]
21:47:33 | 2 of 2 OK created table model public.member_latest_messaging_status.. [SELECT 11529134 in 400.11s]
21:47:34 | 
21:47:34 | Finished running 2 table models in 449.72s.

Completed successfully

Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
```

### Schema tests
```
$ pipenv run dbt test --schema --models tag:core --target prod_warning
Running with dbt=0.18.1
Found 55 models, 104 tests, 3 snapshots, 0 analyses, 143 macros, 0 operations, 0 seed files, 26 sources

21:48:06 | Concurrency: 4 threads (target='prod_warning')
21:48:06 | 
21:48:06 | 1 of 15 START test accepted_values_member_latest_messaging_status_sms_list_status__active__less__pending__stop__unsubscribe__undeliverable__unknown__not_opted_in [RUN]
21:48:06 | 2 of 15 START test not_null_member_latest_inbound_sms_engagement_last_inbound_sms_engagement_flag [RUN]
21:48:06 | 3 of 15 START test not_null_member_latest_inbound_sms_engagement_last_inbound_sms_macro [RUN]
21:48:06 | 4 of 15 START test not_null_member_latest_inbound_sms_engagement_last_inbound_sms_topic [RUN]
21:48:07 | 4 of 15 PASS not_null_member_latest_inbound_sms_engagement_last_inbound_sms_topic [PASS in 1.03s]
21:48:07 | 5 of 15 START test not_null_member_latest_inbound_sms_engagement_northstar_id [RUN]
21:48:07 | 2 of 15 PASS not_null_member_latest_inbound_sms_engagement_last_inbound_sms_engagement_flag [PASS in 1.05s]
21:48:07 | 6 of 15 START test not_null_member_latest_messaging_status_created_at [RUN]
21:48:07 | 3 of 15 PASS not_null_member_latest_inbound_sms_engagement_last_inbound_sms_macro [PASS in 1.09s]
21:48:07 | 7 of 15 START test not_null_member_latest_messaging_status_email_newsletter_subscriptions [RUN]
21:48:08 | 5 of 15 PASS not_null_member_latest_inbound_sms_engagement_northstar_id [PASS in 0.90s]
21:48:08 | 8 of 15 START test not_null_member_latest_messaging_status_email_sub_status [RUN]
21:48:19 | 1 of 15 PASS accepted_values_member_latest_messaging_status_sms_list_status__active__less__pending__stop__unsubscribe__undeliverable__unknown__not_opted_in [PASS in 13.51s]
21:48:19 | 7 of 15 PASS not_null_member_latest_messaging_status_email_newsletter_subscriptions [PASS in 12.41s]
21:48:19 | 6 of 15 PASS not_null_member_latest_messaging_status_created_at...... [PASS in 12.46s]
21:48:19 | 8 of 15 PASS not_null_member_latest_messaging_status_email_sub_status [PASS in 11.58s]
21:48:19 | 9 of 15 START test not_null_member_latest_messaging_status_most_recent_all_actions [RUN]
21:48:19 | 10 of 15 START test not_null_member_latest_messaging_status_most_recent_member_event_log_action [RUN]
21:48:19 | 11 of 15 START test not_null_member_latest_messaging_status_northstar_id [RUN]
21:48:19 | 12 of 15 START test not_null_member_latest_messaging_status_sms_list_status [RUN]
21:48:21 | 11 of 15 PASS not_null_member_latest_messaging_status_northstar_id... [PASS in 1.40s]
21:48:21 | 13 of 15 START test not_null_member_latest_messaging_status_sms_sub_status [RUN]
21:48:21 | 12 of 15 PASS not_null_member_latest_messaging_status_sms_list_status [PASS in 1.64s]
21:48:21 | 14 of 15 START test unique_member_latest_inbound_sms_engagement_northstar_id [RUN]
21:48:21 | 10 of 15 FAIL 176323 not_null_member_latest_messaging_status_most_recent_member_event_log_action [FAIL 176323 in 1.88s]
21:48:21 | 15 of 15 START test unique_member_latest_messaging_status_northstar_id [RUN]
21:48:22 | 9 of 15 FAIL 106782 not_null_member_latest_messaging_status_most_recent_all_actions [FAIL 106782 in 2.27s]
21:48:22 | 13 of 15 PASS not_null_member_latest_messaging_status_sms_sub_status. [PASS in 1.54s]
21:48:23 | 14 of 15 PASS unique_member_latest_inbound_sms_engagement_northstar_id [PASS in 1.76s]
21:49:51 | 15 of 15 PASS unique_member_latest_messaging_status_northstar_id..... [PASS in 89.89s]
21:49:51 | 
21:49:51 | Finished running 15 tests in 107.93s.

Completed with 2 errors and 0 warnings:

Failure in test not_null_member_latest_messaging_status_most_recent_member_event_log_action (models/marts/core/core.yml)
  Got 176323 results, expected 0.

  compiled SQL at ../../docs/compiled/ds_dbt/models/marts/core/core.yml/schema_test/not_null_member_latest_messaging_status_7e3cffdfa9fd6c339ec7bbf772a42a52.sql

Failure in test not_null_member_latest_messaging_status_most_recent_all_actions (models/marts/core/core.yml)
  Got 106782 results, expected 0.

  compiled SQL at ../../docs/compiled/ds_dbt/models/marts/core/core.yml/schema_test/not_null_member_latest_messaging_status_most_recent_all_actions.sql

Done. PASS=13 WARN=0 ERROR=2 SKIP=0 TOTAL=15
```

# Relevant Links
[Pivotal Card #176546694](https://www.pivotaltracker.com/story/show/176546694)

# Pending Tasks / Notes

### Notes

There are 2 schema tests that are not completing successfully: `not_null_member_latest_messaging_status_most_recent_member_event_log_action` and `not_null_member_latest_messaging_status_most_recent_all_actions`. I believe these may be related to 2 main reasons:
-  a discrepancy in total count of users between the `users` and the `member_event_log` tables.
-  edge cases where a user is subscribed to email but hasn't interacted in any other way.

### Pending

- Creating and testing the Snapshot table.

### CODE REVIEW

**Comment by ghangas-ds** [comment]
@rapala61 ran this locally against quasar qa and the output looks good to me. 

Only thing that I noticed is that this materializes as a view currently. I think that's probably just because you're still updating all of the yml stuff still (so disregard this if that's the case!)

One conceptual question: Do you think "Customer Not Subscribed" will be confusing for folks? Do you think that will get confused with "Customer Unsubscribed?" Should this be "Customer Never Subscribed".   My aim is to make this as clear as possible and eliminate as much potential for mistakes.  (I'll also ask Anthony!)

**Comment by ghangas-ds** [comment]
> @rapala61 ran this locally against quasar qa and the output looks good to me.
> 
> Only thing that I noticed is that this materializes as a view currently. I think that's probably just because you're still updating all of the yml stuff still (so disregard this if that's the case!)
> 
> One conceptual question: Do you think "Customer Not Subscribed" will be confusing for folks? Do you think that will get confused with "Customer Unsubscribed?" Should this be "Customer Never Subscribed". My aim is to make this as clear as possible and eliminate as much potential for mistakes. (I'll also ask Anthony!)

following up here. Let's go with “customer_never_subscribed” instead of customer_not_subscribed within the email_status and sms_status fields when there are null values

**Review by ghangas-ds — APPROVED** [review]

**Comment by rapala61** [comment]
@ghangas-ds This is ready for a full review 👀 . I'll add the Snapshot in a different PR to make this one more manageable!

**Comment by ghangas-ds** [comment]
Looks really good to me. 

In terms of these 2 tests failing, can we add in logic that basically adds in the created_at date as the last known action if we cannot identify any others? To me that feels like the most reasonable way of handling those scenarios. What are your thoughts?

not_null_member_latest_messaging_status_most_recent_member_event_log_action and not_null_member_latest_messaging_status_most_recent_all_actions

**Comment by rapala61** [comment]
> @rapala61 Looks really good to me.
> 
> In terms of these 2 tests failing, can we add in logic that basically adds in the created_at date as the last known action if we cannot identify any others? To me that feels like the most reasonable way of handling those scenarios. What are your thoughts?
> 
> not_null_member_latest_messaging_status_most_recent_member_event_log_action and not_null_member_latest_messaging_status_most_recent_all_actions

Added the logic and tests passed successfully! 🎉 

```
$ pipenv run dbt test --schema --models tag:core --target prod_warning
Running with dbt=0.18.1
Found 55 models, 104 tests, 3 snapshots, 0 analyses, 143 macros, 0 operations, 0 seed files, 26 sources

11:29:29 | Concurrency: 4 threads (target='prod_warning')
11:29:29 | 
11:29:29 | 1 of 15 START test accepted_values_member_latest_messaging_status_sms_list_status__active__less__pending__stop__unsubscribe__undeliverable__unknown__not_opted_in [RUN]
11:29:29 | 2 of 15 START test not_null_member_latest_inbound_sms_engagement_last_inbound_sms_engagement_flag [RUN]
11:29:29 | 3 of 15 START test not_null_member_latest_inbound_sms_engagement_last_inbound_sms_macro [RUN]
11:29:29 | 4 of 15 START test not_null_member_latest_inbound_sms_engagement_last_inbound_sms_topic [RUN]
11:29:30 | 3 of 15 PASS not_null_member_latest_inbound_sms_engagement_last_inbound_sms_macro [PASS in 0.98s]
11:29:30 | 5 of 15 START test not_null_member_latest_inbound_sms_engagement_northstar_id [RUN]
11:29:30 | 2 of 15 PASS not_null_member_latest_inbound_sms_engagement_last_inbound_sms_engagement_flag [PASS in 1.01s]
11:29:30 | 6 of 15 START test not_null_member_latest_messaging_status_created_at [RUN]
11:29:30 | 4 of 15 PASS not_null_member_latest_inbound_sms_engagement_last_inbound_sms_topic [PASS in 1.03s]
11:29:30 | 7 of 15 START test not_null_member_latest_messaging_status_email_newsletter_subscriptions [RUN]
11:29:31 | 5 of 15 PASS not_null_member_latest_inbound_sms_engagement_northstar_id [PASS in 0.92s]
11:29:31 | 8 of 15 START test not_null_member_latest_messaging_status_email_sub_status [RUN]
11:29:42 | 6 of 15 PASS not_null_member_latest_messaging_status_created_at...... [PASS in 11.85s]
11:29:42 | 8 of 15 PASS not_null_member_latest_messaging_status_email_sub_status [PASS in 10.96s]
11:29:42 | 9 of 15 START test not_null_member_latest_messaging_status_most_recent_all_actions [RUN]
11:29:42 | 7 of 15 PASS not_null_member_latest_messaging_status_email_newsletter_subscriptions [PASS in 11.84s]
11:29:42 | 10 of 15 START test not_null_member_latest_messaging_status_most_recent_member_event_log_action [RUN]
11:29:42 | 11 of 15 START test not_null_member_latest_messaging_status_northstar_id [RUN]
11:29:42 | 1 of 15 PASS accepted_values_member_latest_messaging_status_sms_list_status__active__less__pending__stop__unsubscribe__undeliverable__unknown__not_opted_in [PASS in 12.90s]
11:29:42 | 12 of 15 START test not_null_member_latest_messaging_status_sms_list_status [RUN]
11:29:43 | 11 of 15 PASS not_null_member_latest_messaging_status_northstar_id... [PASS in 1.47s]
11:29:43 | 13 of 15 START test not_null_member_latest_messaging_status_sms_sub_status [RUN]
11:29:43 | 12 of 15 PASS not_null_member_latest_messaging_status_sms_list_status [PASS in 1.51s]
11:29:43 | 14 of 15 START test unique_member_latest_inbound_sms_engagement_northstar_id [RUN]
11:29:43 | 10 of 15 PASS not_null_member_latest_messaging_status_most_recent_member_event_log_action [PASS in 1.59s]
11:29:43 | 15 of 15 START test unique_member_latest_messaging_status_northstar_id [RUN]
11:29:43 | 9 of 15 PASS not_null_member_latest_messaging_status_most_recent_all_actions [PASS in 1.69s]
11:29:44 | 13 of 15 PASS not_null_member_latest_messaging_status_sms_sub_status. [PASS in 1.42s]
11:29:45 | 14 of 15 PASS unique_member_latest_inbound_sms_engagement_northstar_id [PASS in 1.58s]
11:31:11 | 15 of 15 PASS unique_member_latest_messaging_status_northstar_id..... [PASS in 87.62s]
11:31:11 | 
11:31:11 | Finished running 15 tests in 104.50s.

Completed successfully

Done. PASS=15 WARN=0 ERROR=0 SKIP=0 TOTAL=15
```

**Pull request merged**
