### PR TITLE
updated dbt-docs.yml

### PR DESCRIPTION
**Pull request by ghangas-ds**
#### What's this PR do?
Adds in the new environment variables for the survey and Google Sheets schema

#### Where should the reviewer start?
review my entries in dbt-docs.yml 

#### What are the relevant tickets?
https://www.pivotaltracker.com/n/projects/2328687/stories/176348823

### CODE REVIEW

**Review by rapala61 — CHANGES_REQUESTED** [review]
Let's remove the .pickle and docs files generated locally.

**Comment by ghangas-ds** [comment]
> Let's remove the .pickle and docs files generated locally.

Oh shoot. Im not sure why that happened. How do I update this to remove?

**Comment by rapala61** [comment]
@ghangas-ds We can pair on this if you want!

**Comment by ghangas-ds** [comment]
> @ghangas-ds We can pair on this if you want!

okay cool! sorry! not sure what i need to update. :/ I will find 30 minutes later this afternoon if thats okay

**Pull request closed without merging**
