### PR TITLE
Updating missing FROM reference in OVRD funnel.

### PR DESCRIPTION
**Pull request by sheyd**
#### What's this PR do?
Updates a missing `FROM` statement in OVRD funnel.
#### Where should the reviewer start?
https://github.com/DoSomething/quasar/compare/ovrd-funnel-fix?expand=1#diff-2fd2e4b27b1897b92488cb54ea6e9614R12
#### How should this be manually tested?
QA
#### What are the relevant tickets?
https://www.pivotaltracker.com/story/show/172254348

### CODE REVIEW

**Comment by blisteringherb** [comment]
I thought the Bertly component got removed? https://github.com/DoSomething/quasar/commit/ee853e07952b040516b973a2b18fc5f836cd6cdb

@sohaibhasan @sheyd

**Comment by sheyd** [comment]
Ah, missed that. The SQL is invalid though, since it still has references to `bc`.

**Comment by sheyd** [comment]
@sohaibhasan Can you confirm the latest commit changes are accurate?

**Comment by sohaibhasan** [comment]
@sheyd Yup! Looks good to me! Thanks for debugging

**Pull request merged**
