### PR TITLE
Feature/add nps model

### PR DESCRIPTION
**Pull request by ghangas-ds**
#### What's this PR do?
This PR adds the NPS (Net promoter score) web survey data into our data model

This combines a static historical file that exists in the survey schema with a Fivetran source data table from Google Sheets (there is a real time export of Typeform to GS) and unions them into one final fact table.

#### Where should the reviewer start?
The source model files live under staging/* . I created this since we eventually want to structure our overall model in [this manner](https://discourse.getdbt.com/t/how-we-structure-our-dbt-projects/355) 

#### How should this be manually tested?

pipenv run dbt run --models staging.* --profile qa
pipenv run dbt run --models member_feedback.* --profile qa

#### Any background context you want to provide?
I think that in order for this to be run in production, we will also need to update some environment variables

export SURVEY_SCHEMA='survey'
export FT_GOOGLE_SHEETS_SCHEMA='ft_google_sheets'

#### What are the relevant tickets?
https://www.pivotaltracker.com/n/projects/2328687

### CODE REVIEW

**Review by rapala61 — COMMENTED** [review]
This looks pretty neat! I have a few comments in regards to the new paradigm we are going to start adopting.

What do you think if instead of  `stg_historical_nps_web` and `stg_typeform_nps_web` being 2 staging models. We make them base models `base_historical_nps_web` & `base_typeform_nps_web` respectively? We can then handle the "net_promoter_cat" logic in these base models; which is where we want to start handling "cleaning" logic.

We can then union both of these into `stg_nps_web_responses`.

For consistency -- where core models must depend on staging models. The `fct_nps_web_responses` model will basically just be a "select * from stg_nps_web_responses"

I wouldn't worry too much about perfect file organization so it can stay the same.

**Comment by ghangas-ds** [comment]
> This looks pretty neat! I have a few comments in regards to the new paradigm we are going to start adopting.
> 
> What do you think if instead of `stg_historical_nps_web` and `stg_typeform_nps_web` being 2 staging models. We make them base models `base_historical_nps_web` & `base_typeform_nps_web` respectively? We can then handle the "net_promoter_cat" logic in these base models; which is where we want to start handling "cleaning" logic.
> 
> We can then union both of these into `stg_nps_web_responses`.
> 
> For consistency -- where core models must depend on staging models. The `fct_nps_web_responses` model will basically just be a "select * from stg_nps_web_responses"
> 
> I wouldn't worry too much about perfect file organization so it can stay the same.



> This looks pretty neat! I have a few comments in regards to the new paradigm we are going to start adopting.
> 
> What do you think if instead of `stg_historical_nps_web` and `stg_typeform_nps_web` being 2 staging models. We make them base models `base_historical_nps_web` & `base_typeform_nps_web` respectively? We can then handle the "net_promoter_cat" logic in these base models; which is where we want to start handling "cleaning" logic.
> 
> We can then union both of these into `stg_nps_web_responses`.
> 
> For consistency -- where core models must depend on staging models. The `fct_nps_web_responses` model will basically just be a "select * from stg_nps_web_responses"
> 
> I wouldn't worry too much about perfect file organization so it can stay the same.

Ah yeah! I think I understand.. basically interpret like this?

base = raw models, no cleaning
stg = staging, basic cleansing

**Comment by ghangas-ds** [comment]
> > This looks pretty neat! I have a few comments in regards to the new paradigm we are going to start adopting.
> > What do you think if instead of `stg_historical_nps_web` and `stg_typeform_nps_web` being 2 staging models. We make them base models `base_historical_nps_web` & `base_typeform_nps_web` respectively? We can then handle the "net_promoter_cat" logic in these base models; which is where we want to start handling "cleaning" logic.
> > We can then union both of these into `stg_nps_web_responses`.
> > For consistency -- where core models must depend on staging models. The `fct_nps_web_responses` model will basically just be a "select * from stg_nps_web_responses"
> > I wouldn't worry too much about perfect file organization so it can stay the same.
> 
> > This looks pretty neat! I have a few comments in regards to the new paradigm we are going to start adopting.
> > What do you think if instead of `stg_historical_nps_web` and `stg_typeform_nps_web` being 2 staging models. We make them base models `base_historical_nps_web` & `base_typeform_nps_web` respectively? We can then handle the "net_promoter_cat" logic in these base models; which is where we want to start handling "cleaning" logic.
> > We can then union both of these into `stg_nps_web_responses`.
> > For consistency -- where core models must depend on staging models. The `fct_nps_web_responses` model will basically just be a "select * from stg_nps_web_responses"
> > I wouldn't worry too much about perfect file organization so it can stay the same.
> 
> Ah yeah! I think I understand.. basically interpret like this?
> 
> base = raw models, no cleaning
> stg = staging, basic cleansing

oh oops nvm i realize what you are saying. Let me try and make some updates and will send back to you for review :) Thank you!

**Comment by ghangas-ds** [comment]
@rapala61 i incorporated the changes but no need to review today. can wait til next week. thank you for your feedback!  the structure you proposed makes good sense!

**Pull request merged**
